### ISSUE TITLE
Scheduled livestreams publish with wrong date

### ISSUE THREAD

**Issue by kauffj** [lbryio/ytsync#114]
I did this livestream last night, but it synced with an October date from when it was originally scheduled.

![signal-2021-11-02-115104_001](https://user-images.githubusercontent.com/530774/139947368-7f3f9214-4502-4766-8fdc-278da79ef8d5.png)

**Comment by tzarebczan** [comment]
This should be fixed now, let us know if you still see it. It may still happen for content that's non live/premiere that has a date changed -  there's one more fix for that to overwrite release times when we get notifications.

**Comment by tzarebczan** [comment]
This is still happening, we'll review the logic again.

**Comment by tzarebczan** [comment]
Should be fixed now...
