### ISSUE TITLE
Ensure ytsync continuous processing / better alerts

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/ytsync#12]
We ran into an issue recently where a bunch of existing channels were not being synced because they were in failed status and also because of some server issues. We should be able to re-try sync in some of these scenarios and provide better errors/notifications when things stop processing server side. 

- [x] Alert us on slack when ytsync dies
- [x] Create dashboard to overview failed channels
- [x] Alert us when the youtube sync wallet runs out of credits
- [x] Address remaining failed videos (details below)

Main error to address `Initial wallet setup failed! Manual Intervention is required.: channel_claim_id: cannot be blank.`

**Comment by nikooo777** [comment]
This is an issue that has to be resolved ASAP.

Most of the work has been done already (3/4 resolved), the last point is pending and will be addressed during the sprint as unplanned work.

**Comment by nikooo777** [comment]
done
