### ISSUE TITLE
Autocrop YouTube thumbnails (eliminate black spaces)

### ISSUE THREAD

**Issue by kauffj** [lbryio/ytsync#15]
See [this page](https://spee.ch/@minutephysics:5) as an example.

`imagemagick mogrify -trim -bordercolor black -fuzz x%` may get you most of the way there, but it's worth running over a decent sample set to ensure it doesn't fail on images that are already pretty black.

**Comment by kauffj** [comment]
@jessopb

**Comment by nikooo777** [comment]
I believe that the job of cropping, resizing, fitting the thumbnails should be done by the displaying client. I'd argue that youtube already had to make this choice years ago and probably picked this kind of size for a reason. I would keep it as such as we can always shrink it client side but we can't un-crop it once it's cropped.
