### ISSUE TITLE
Update all YT claims with new metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/ytsync#18]
This will serve as the ytsyc issue to implement the below and an epic to track types/sdk required changes. When the sdk tickets are filed, I'll update it.

1)  Setup a process to perform claim updates, preferably in batch mode 
(https://github.com/lbryio/lbry/issues/1821). If easy update mode is available (https://github.com/lbryio/lbry/issues/1423), use it, if not, read from existing claim data. This also includes grabbing the sdblob for each claim in order to populate some of the new file related fields. 

2) From the sdblob, grab the filename and file size to populate name/size in https://github.com/lbryio/types/issues/9. 

3) Grab video length from the YouTube api to populate length in https://github.com/lbryio/types/issues/9

4) Grab published date from YouTube api  to populate releaseTime in https://github.com/lbryio/types/issues/13

5) Grab category/tags from YouTube api to populate in https://github.com/lbryio/types/issues/15 or https://github.com/lbryio/types/issues/16

6) Grab language from YouTube api and populate language on claim metadata

7) Research other relevant youtube API data that may require new types/sdk entries.

**Comment by alyssaoc** [comment]
What is the status of this as a blocker

**Comment by kauffj** [comment]
@nikooo777 

1) Can this ticket be updated to include adding the relevant creator metadata as well?
2) Can you please tag @lbryio/appsquad as soon as the first new metadata exists in the blockchain?

**Comment by tzarebczan** [comment]
Niko and I ran through this today and all the fields we need are available in the YouTube api. The email we'll populate from their LBRY account. We'd have to link back their featured content URL to a published file which is the trickiest part since we'll need to know the URL beforehand or update it later. 

I'll get a full sample of a channel publish to the app squad soon.

**Comment by kauffj** [comment]
@nikooo777 this just came up in a discussion with @robvsmith: we should pull in the tags already set in internal-apis and apply those as well

**Comment by tzarebczan** [comment]
This is completed, please reopen if that's not the case @nikooo777
