### ISSUE TITLE
Support publishing with new metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/ytsync#19]
Requires similar issues to be completed on types/lbrysdk as https://github.com/lbryio/ytsync/issues/18 
Not sure if we want to start publishing with new metadata after it's immediately available or once the full set is ready (if we publish immediately, we'll need to update the claims later with other metadata)

1) From the download file, grab the filename and file size to populate name/size in https://github.com/lbryio/types/issues/9. 

2) Grab video length from the YouTube api (or from lbry-sdk process if that's easier) to populate length in https://github.com/lbryio/types/issues/9

3) Grab published date from YouTube api  to populate releaseTime in https://github.com/lbryio/types/issues/13

4) Grab category/tags from YouTube api to populate in https://github.com/lbryio/types/issues/15 or https://github.com/lbryio/types/issues/16

5) Grab language from YouTube api and populate language on claim metadata

6) Research other relevant youtube API data that may require new types/sdk entries.

7) Store any of these fields in the synced videos table as needed

**Comment by nikooo777** [comment]
Finished!
