### ISSUE TITLE
Fix "abandoned" status syncs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/ytsync#21]
Looks like a bunch of youtube syncs were set to abandoned status prematurely because they were not rewards approved. Not sure how to best handle this yet - but we may have some YT sync users that get set to rewards disabled initially, and then set to approved. Some of these were synced, and then set to abandoned.

**Comment by nikooo777** [comment]
steps to take:

- Have a cron job loop through all the abandoned channels, if the associated user has been manually re-enabled then put the channel back to pending/queued
- To decide whether it's pending or queued we must:
- [ ] Cross reference from the notification table to understand if a user had previously granted syncing rights
- [ ] Add a flag or something to better identify abandoned channels that never granted consent vs abandoned channels that previously granted consent

additionally (bonus point):
- Better handle channels that get wiped by youtube and thus end up with 0 uploaded videos (yet still have all their content on lbry and aren't banned from youtube)

**Comment by tzarebczan** [comment]
Sounds like this was almost completed...we reset the current ones be we need a way to check if users go from banned > approved status and fix their status automatically...is that right?
