### ISSUE TITLE
Delay syncing video if newly posted / not post processed

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/ytsync#3]
@tzarebczan commented on [Tue Sep 11 2018](https://github.com/lbryio/lbry.go/issues/42)

I think we may sometimes run into a scenario where we sync a video before it is post-processed in 720P+ on YouTube so we end up syncing a lower quality version. We should check when the video was posted, and if it's very recent (not sure what the timing for post-processing looks like), delay download/publish until the next iteration.

**Comment by tzarebczan** [comment]
Haven't seen this happen.
