### ISSUE TITLE
transfer kinks (support user with duplicate videos)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/ytsync#42]
- [x] videos published before transfer are not marked as transferred - this causes the video to fail in transferring. This happens if there are new videos after we got an address/pubkey

- [x] support list needs to use the default account id - otherwise it will try to abandon supports for transferred videos and fail to sync. 

- [x] if the process breaks / needs restart, supports need to be resent manually

- [x] 571b35609b90cffceafee38242a6c48f9499c276 had duplicate synced_videos, so the counts were wrong

- [x] when we try to delete some content after transfer, things fail -  https://lbryians.slack.com/archives/D5W0D8ZJP/p1569617590246000

**Comment by nikooo777** [comment]
last issue in there needs to be resolved client side, I will provide the fresh list of abandon calls to execute

**Comment by kauffj** [comment]
Assigning to @tzarebczan since the only remaining task is a support issue.

**Comment by tzarebczan** [comment]
@conmech was fixed, but the above comment about 571b35609b90cffceafee38242a6c48f9499c276 was related to a different channel and the synced videos table (had duplicate entries, but don't think the videos themselves were duplicated). Maybe we can check if this is happening more often and open an issue.

**Comment by kauffj** [comment]
@tzarebczan moving this back to inactive to work on other priorities
