### ISSUE TITLE
Language reporting for youtube syncs (add column + fix accuracy)

### ISSUE THREAD

**Issue by kauffj** [lbryio/ytsync#86]
It'd be useful to give reports to certain community members that show recent YouTube syncs from certain countries. This could be done by either setting a column on `youtube_data` or by setting it on the account itself. 

This needs to be set properly on content and on the youtuber.

If this can already be done, tell @tzarebczan.

**Comment by tzarebczan** [comment]
Also check the ML tool - it's setting the language incorrectly for taiwanese content as EN/US sometimes.

**Comment by tzarebczan** [comment]
Also, make sure to set simplified vs traditional chinese codes https://github.com/lbryio/types/issues/44

**Comment by kauffj** [comment]
Tom suggested fixing the accuracy by adding collection of the language at the time of channel sync/creation.
