### ISSUE TITLE
force h264 codec on ffmpeg

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/ytsync#91]
There was a recent video that was AV1 codec. Need to make sure we are forcing h264

**Comment by tzarebczan** [comment]
Also force stereo audio - 5.1 is not supported

**Comment by kauffj** [comment]
@tzarebczan will attach a few examples

**Comment by tzarebczan** [comment]
Here's a more recent example. These will not play video on FF. https://odysee.com/@CrackerMilk:6/movember:2

**Comment by tzarebczan** [comment]
Both these failure cases should be fixed for future syncs
